version: "3"

services:
  database:
    image: postgres:alpine
    container_name: database_ecommerce_v1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database_ecommerce_v1
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: ecommerce_v1
  #   restart: always
  #   ports:
  #     - 3333:3333
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #     - database-test
  #   depends_on:
  #     - database
  #     - database-test

volumes:
  pgdata:
    driver: local
